/**
*   @file    CanTrcv_43_tja1145a[!IF "var:defined('postBuildVariant')"!]_[!"$postBuildVariant"!][!ENDIF!]_Cfg.c
*   @version 0.8.0
*
*   @brief   AUTOSAR CanTrcv_43_tja1145a - module interface
*   @details Transceiver configuration generated by user settings.
*
*   @addtogroup CanTrcv_tja1145a_Driver
*   @{
*/
/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : 
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 0.8.0
*   Build Version        : S32K3_RTD_0_8_0_D2305_ASR_REL_4_7_REV_0000_20230524
*
*   (c) Copyright 2020 - 2023 NXP Semiconductors
*   All Rights Reserved.
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/

#ifdef __cplusplus
extern "C"{
#endif

/**
* @file           CanTrcv_43_tja1145a_Cfg.c
*/
/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "CanTrcv_43_tja1145a.h"
#if (CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
#include "Dem.h"
#endif
#ifdef CANTRCV_43_TJA1145A_WAKEUP_SUPPORT
    #if (CANTRCV_43_TJA1145A_WAKEUP_SUPPORT == STD_ON)
        #include "EcuM.h"
    #endif
#endif

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CANTRCV_43_TJA1145A_VENDOR_ID_CFG_C                      43
#define CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_C       4
#define CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_C       7
#define CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_CFG_C    0
#define CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_CFG_C               0
#define CANTRCV_43_TJA1145A_SW_MINOR_VERSION_CFG_C               8
#define CANTRCV_43_TJA1145A_SW_PATCH_VERSION_CFG_C               0

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
/* Check if current file and CanTrcv_43_tja1145a header file are of the same vendor */
#if (CANTRCV_43_TJA1145A_VENDOR_ID_CFG_C != CANTRCV_43_TJA1145A_VENDOR_ID)
    #error "CanTrcv_43_tja1145a_Cfg.c and CanTrcv_43_tja1145a.h have different vendor ids"
#endif
/* Check if current file and CanTrcv_43_tja1145a header file are of the same Autosar version */
#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_C    != CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_C    != CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_CFG_C != CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION))
    #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_Cfg.c and CanTrcv_43_tja1145a.h are different"
#endif
/* Check if current file and CanTrcv_43_tja1145a header file are of the same Software version */
#if ((CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_CFG_C != CANTRCV_43_TJA1145A_SW_MAJOR_VERSION) || \
     (CANTRCV_43_TJA1145A_SW_MINOR_VERSION_CFG_C != CANTRCV_43_TJA1145A_SW_MINOR_VERSION) || \
     (CANTRCV_43_TJA1145A_SW_PATCH_VERSION_CFG_C != CANTRCV_43_TJA1145A_SW_PATCH_VERSION))
    #error "Software Version Numbers of CanTrcv_43_tja1145a_Cfg.c and CanTrcv_43_tja1145a.h are different"
#endif

#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
    /* Check if current file and DEM header file are of the same version */
	#if (CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
		#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_C != DEM_AR_RELEASE_MAJOR_VERSION) || \
            (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_C != DEM_AR_RELEASE_MINOR_VERSION))
            #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_Cfg.c and Dem.h are different"
        #endif
	#endif

    /* Check if current file and ECUM header file are of the same version */
    #if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_C != ECUM_AR_RELEASE_MAJOR_VERSION) || \
         (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_C != ECUM_AR_RELEASE_MINOR_VERSION))
        #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_Cfg.c and EcuM.h are different"
    #endif
#endif
/*==================================================================================================
*                                      GLOBAL VARIABLES
==================================================================================================*/

/*==================================================================================================
*                          LOCAL TYPEDEFS (STRUCTURES, UNIONS, ENUMS)
==================================================================================================*/

/*==================================================================================================
*                                      LOCAL CONSTANTS
==================================================================================================*/

/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/
[!NOCODE!][!//
[!VAR "DeviceCount" = "num:i(count(CanTrcvConfigSet/CanTrcvChannel/*)) - 1"!][!//
[!ENDNOCODE!][!//
/**
* @brief Configuration of ECUM wake up source for reporting different wake up events and DEM error reporting.
*/
const CanTrcv_43_tja1145a_EcuMReportType CanTrcv_43_tja1145a_EcuMReportConfig[] =
{
[!FOR "DeviceIdx" = "0" TO "$DeviceCount"!][!//
[!SELECT "CanTrcvConfigSet/CanTrcvChannel/*[CanTrcvChannelId = $DeviceIdx]"!][!//
    {
[!IF "(node:exists(CanTrcvWakeupSourceRef) = 'true') and (node:value(CanTrcvWakeupSourceRef) != '')"!][!//
        .WakeupSourceConfig =
        {
            .WakeupSourceEn = TRUE,
            .EcuMWakeupSource = EcuMConf_EcuMWakeupSource_[!"node:ref(node:value(CanTrcvWakeupSourceRef))/@name"!]
        },
[!ELSE!][!//
        .WakeupSourceConfig =
        {
            .WakeupSourceEn = FALSE,
            .EcuMWakeupSource = (EcuM_WakeupSourceType) 0UL
        },
[!ENDIF!][!//
[!IF "(node:exists(CanTrcvPorWakeupSourceRef) = 'true') and (node:value(CanTrcvPorWakeupSourceRef) != '')"!][!//
        .PorWakeupSourceConfig =
        {
            .WakeupSourceEn = TRUE,
            .EcuMWakeupSource = EcuMConf_EcuMWakeupSource_[!"node:ref(node:value(CanTrcvPorWakeupSourceRef))/@name"!]
        },
[!ELSE!][!//
        .PorWakeupSourceConfig =
        {
            .WakeupSourceEn = FALSE,
            .EcuMWakeupSource = (EcuM_WakeupSourceType) 0UL
        },
[!ENDIF!][!//
[!IF "(node:exists(CanTrcvSyserrWakeupSourceRef) = 'true') and (node:value(CanTrcvSyserrWakeupSourceRef) != '')"!][!//
        .SysErrWakeupSourceConfig =
        {
            .WakeupSourceEn = TRUE,
            .EcuMWakeupSource = EcuMConf_EcuMWakeupSource_[!"node:ref(node:value(CanTrcvSyserrWakeupSourceRef))/@name"!]
        },
[!ELSE!][!//
        .SysErrWakeupSourceConfig =
        {
            .WakeupSourceEn = FALSE,
            .EcuMWakeupSource = (EcuM_WakeupSourceType) 0UL
        },
[!ENDIF!][!//
    #if (CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
[!IF "node:exists(CanTrcvDemEventParameterRefs/CANTRCV_E_BUS_ERROR)"!][!//
[!IF "node:refvalid(CanTrcvDemEventParameterRefs/CANTRCV_E_BUS_ERROR)"!][!//
        .DemErrorReportConfig =
        {
            .state = (uint32) STD_ON,
            .id = DemConf_DemEventParameter_[!"node:ref(node:value(CanTrcvDemEventParameterRefs/CANTRCV_E_BUS_ERROR))/@name"!]
        }
[!ELSE!][!//
    [!ERROR "Invalid reference for CanTrcvDemEventParameterRefs/CANTRCV_E_BUS_ERROR"!]
[!ENDIF!][!//
[!ELSE!][!//
        .DemErrorReportConfig =
        {
            .state = (uint32) STD_OFF,
            .id = 0U
        }
[!ENDIF!][!//
    #endif
    }[!IF "$DeviceIdx < $DeviceCount"!],[!ENDIF!]
[!ENDSELECT!][!//
[!ENDFOR!]
};
#ifdef __cplusplus
}
#endif

/** @} */
