/**
*   @file    CanTrcv_43_tja1145a[!IF "var:defined('postBuildVariant')"!]_[!"$postBuildVariant"!][!ENDIF!]_PBcfg.c
*   @version 0.8.0
*
*   @brief   AUTOSAR CanTrcv_43_tja1145a - module interface
*   @details Transceiver configuration generated by user settings.
*
*   @addtogroup CanTrcv_tja1145a_Driver
*   @{
*/
/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : 
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 0.8.0
*   Build Version        : S32K3_RTD_0_8_0_D2305_ASR_REL_4_7_REV_0000_20230524
*
*   (c) Copyright 2020 - 2023 NXP Semiconductors
*   All Rights Reserved.
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/

#ifdef __cplusplus
extern "C"{
#endif

/**
* @file           CanTrcv_43_tja1145a[!IF "var:defined('postBuildVariant')"!]_[!"$postBuildVariant"!][!ENDIF!]_PBcfg.c
*/

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "CanTrcv_43_tja1145a.h"
#if (CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
#include "Dem.h"
#endif
[!AUTOSPACING!]

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CANTRCV_43_TJA1145A_VENDOR_ID_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C                      43
#define CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C       4
#define CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C       7
#define CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C    0
#define CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C               0
#define CANTRCV_43_TJA1145A_SW_MINOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C               8
#define CANTRCV_43_TJA1145A_SW_PATCH_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C               0

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
/* Check if current file and CanTrcv_43_tja1145a.h are of the same vendor */
#if (CANTRCV_43_TJA1145A_VENDOR_ID_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_VENDOR_ID)
    #error "CanTrcv_43_tja1145a_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBcfg.c and CanTrcv_43_tja1145a.h have different vendor ids"
#endif
/* Check if current file and CanTrcv_43_tja1145a.h are of the same Autosar version */
#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION))
    #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBcfg.c and CanTrcv_43_tja1145a.h are different"
#endif
/* Check if current file and CanTrcv_43_tja1145a.h are of the same Software version */
#if ((CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_SW_MAJOR_VERSION) || \
     (CANTRCV_43_TJA1145A_SW_MINOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_SW_MINOR_VERSION) || \
     (CANTRCV_43_TJA1145A_SW_PATCH_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != CANTRCV_43_TJA1145A_SW_PATCH_VERSION))
    #error "Software Version Numbers of CanTrcv_43_tja1145a_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBcfg.c and CanTrcv_43_tja1145a.h are different"
#endif

#if (CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS == STD_OFF)
	/* Check if current file and Dem.h are of the same Software version */
	#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != DEM_AR_RELEASE_MAJOR_VERSION) || \
		(CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBCFG_C != DEM_AR_RELEASE_MINOR_VERSION))
		#error "AutoSar Version Numbers of CanTrcv_43_tja1145a_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!]_[!ENDIF!]PBcfg.c and Dem.h are different"
	#endif
#endif

/*==================================================================================================
*                                      GLOBAL VARIABLES
==================================================================================================*/

/*==================================================================================================
*                          LOCAL TYPEDEFS (STRUCTURES, UNIONS, ENUMS)
==================================================================================================*/

/*==================================================================================================
*                                      LOCAL CONSTANTS
==================================================================================================*/
[!IF "((IMPLEMENTATION_CONFIG_VARIANT != 'VariantPostBuild') and (variant:size()>1)) or (IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
[!SELECT "CanTrcvConfigSet"!]
[!NOCODE!][!//
[!VAR "CfgMax" = "num:i(count(CanTrcvChannel/* )) - 1"!]
[!ENDNOCODE!][!//

[!CODE!]
#define CANTRCV_43_TJA1145A_START_SEC_CONFIG_DATA_32
#include "CanTrcv_43_tja1145a_MemMap.h"

[!FOR "ConfigIdx" = "0" TO "$CfgMax"!]
/**
* @brief SPI sequence for communication with device ID [!"$ConfigIdx"!].
*/
static const Spi_SequenceType SpiSequence_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!][!WS!]=[!WS!][!"num:i(node:ref(CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvAccess/CanTrcvSpiSequence/CanTrcvSpiSequenceName)/SpiSequenceId)"!]U;

[!ENDFOR!]
#define CANTRCV_43_TJA1145A_STOP_SEC_CONFIG_DATA_32
#include "CanTrcv_43_tja1145a_MemMap.h"

#define CANTRCV_43_TJA1145A_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "CanTrcv_43_tja1145a_MemMap.h"

[!FOR "ConfigIdx" = "0" TO "$CfgMax"!]
/**
* @brief Configuration of SPI interface for communication with device ID [!"$ConfigIdx"!].
*/
static const CanTrcv_tja1145a_SpiConfigType SpiConfig_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!][!WS!]=
{
	.SpiChannel = [!"num:i(node:ref(CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvAccess/CanTrcvSpiSequence/SpiChannelRef)/SpiChannelId)"!]U,
    .SpiExtension = (const void*) &SpiSequence_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!]

};

[!ENDFOR!]

[!FOR "ConfigIdx" = "0" TO "$CfgMax"!]
[!VAR "IdExtended" = "CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnCanIdIsExtended"!]
[!VAR "PnEnabled" = "CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnEnabled"!]
/**
* @brief Configuration of TJA1145A with ID [!"$ConfigIdx"!].
*/
static const CanTrcv_tja1145a_DeviceConfigType DevConfig_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!][!WS!]=
{
	.CanConfig =
	{
		.WufId = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameCanId"!]U,
		.WufIdMask = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameCanIdMask"!]U,
		.Dlc = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDlc"!]U,
		.DataRate = TJA1145A_DR_[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvBaudRate"!]KBITS,
		.WufEval = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/WufPattern"!],
		.IdFormat = [!IF "$IdExtended = 'true'"!][!WS!]TJA1145A_29BIT_IDENTIFIER[!ELSE!][!WS!]TJA1145A_11BIT_IDENTIFIER[!ENDIF!],
		.DataMasks = 
		{
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask1"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask2"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask3"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask4"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask5"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask6"!]U,
			[!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvPnFrameDataMaskSpec/CanTrcvPnFrameDataMask7"!]U
		},
		.PnMode = [!IF "$PnEnabled = 'true'"!][!WS!]TJA1145A_PN_ENABLED[!ELSE!][!WS!]TJA1145A_PN_DISABLED[!ENDIF!],
		.FdConfig = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvPartialNetwork/CanTrcvFdEnable"!]
	},
	.WuConfig =
	{
		.CanBusWuMode = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/WuConfig/CanBusWuConfig"!],
		.WuPinMode = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/WuConfig/WakePinConfig"!]
	},
	.EventConfig =
	{
		.OvertempDetectionEnable = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/EventCaptureConfig/OvertempDetection)"!],
		.SpiFailureDetectionEnable = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/EventCaptureConfig/SpiFailureDetection)"!],
		.CanBusSilenceDetectionEnable = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/EventCaptureConfig/CanBusSilenceDetection)"!],
		.CanFailureDetectionEnable = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/EventCaptureConfig/CanBusFailureDetection)"!]
	},
	.VccUvConfig = [!"CanTrcvChannel/*[position()=$ConfigIdx + 1]/EventCaptureConfig/vccUvDetection"!],
	.LockControl =
	{
		.LockRange06h09h = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange06h09h)"!],
		.LockRange10h1Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange10h1Fh)"!],
		.LockRange20h2Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange20h2Fh)"!],
		.LockRange30h3Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange30h3Fh)"!],
		.LockRange40h4Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange40h4Fh)"!],
		.LockRange50h5Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange50h5Fh)"!],
		.LockRange68h6Fh = [!"text:toupper(CanTrcvChannel/*[position()=$ConfigIdx + 1]/LockControl/LockRange68h6Fh)"!]
	},
[!NOCODE!]
	[!VAR "trcvInitState" = "'CANTRCV_TRCVMODE_NORMAL'"!]
	[!IF "node:value(CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvInitState) = 'CANTRCV_OP_MODE_STANDBY'"!]
		[!VAR "trcvInitState" = "'CANTRCV_TRCVMODE_STANDBY'"!]
	[!ELSEIF "node:value(CanTrcvChannel/*[position()=$ConfigIdx + 1]/CanTrcvInitState) = 'CANTRCV_OP_MODE_SLEEP'"!]
		[!VAR "trcvInitState" = "'CANTRCV_TRCVMODE_SLEEP'"!]
	[!ENDIF!]
[!ENDNOCODE!][!//
	.InitState = [!"$trcvInitState"!]
};

[!ENDFOR!]
/**
* @brief List of configurations, one configuration per instance.
*/
static const CanTrcv_tja1145a_ConfigurationDataType ConfigList_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!][] =
{
[!FOR "ConfigIdx" = "0" TO "$CfgMax"!]
	{
		.SpiConfig = &SpiConfig_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!],
		.DeviceConfig = &DevConfig_[!"$ConfigIdx"!]_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!]
		
	}[!IF "$ConfigIdx < $CfgMax"!],[!ENDIF!][!//

[!ENDFOR!]
};

[!ENDCODE!]
[!ENDSELECT!]
[!ENDIF!]
/*==================================================================================================
*                                      GLOBAL CONSTANTS
==================================================================================================*/
[!NOCODE!]
[!IF "var:defined('postBuildVariant')"!]
    [!VAR "postBuildVariantNameUnderscore" = "concat('_',$postBuildVariant)"!]
[!ELSE!]
    [!VAR "postBuildVariantNameUnderscore" = "string(null)"!]
[!ENDIF!]
[!VAR "CanTrcvConfiguredPartitions" = "num:i((count(CanTrcvGeneral/CanTrcvEcucPartitionRef/*)))"!]
[!IF "((IMPLEMENTATION_CONFIG_VARIANT != 'VariantPostBuild') and (variant:size()>1)) or (IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild')"!]
    [!IF "$CanTrcvConfiguredPartitions > 0"!]
        [!VAR "CanTrcvPartitionIdx" = "0"!]
        [!LOOP "CanTrcvGeneral/CanTrcvEcucPartitionRef/*"!]
            [!VAR "CanTrcvPartitionIdx" = "$CanTrcvPartitionIdx + 1"!]
            [!VAR "currentPartition" = "substring-after(substring-after(., 'EcuC/EcuC/'), '/')"!]
            [!CODE!]
/**
* @brief Driver configuration structure.
*/
const CanTrcv_43_tja1145a_DriverConfigType[!WS!]CanTrcv_43_tja1145a_Config[!"$postBuildVariantNameUnderscore"!]_[!"$currentPartition"!] =
{
    .DeviceNum = [!"num:i(count(CanTrcvConfigSet/CanTrcvChannel/*))"!]U,
	.ConfigData = ConfigList_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!]

};

            [!ENDCODE!]
        [!ENDLOOP!]
    [!ELSE!]
        [!CODE!]
/**
* @brief Driver configuration structure.
*/
const CanTrcv_43_tja1145a_DriverConfigType[!WS!]CanTrcv_43_tja1145a_Config[!"$postBuildVariantNameUnderscore"!] =
{
    .DeviceNum = [!"num:i(count(CanTrcvConfigSet/CanTrcvChannel/*))"!]U,
	.ConfigData = ConfigList_[!IF "var:defined('postBuildVariant')"!][!"$postBuildVariant"!][!ENDIF!]
	
};

        [!ENDCODE!]
    [!ENDIF!]
[!ENDIF!]

#define CANTRCV_43_TJA1145A_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "CanTrcv_43_tja1145a_MemMap.h"
[!ENDNOCODE!]

#ifdef __cplusplus
}
#endif

/** @} */
