/**
*   @file    Can_43_LLCE_Cfg.h
*   @version 1.0.7
*
*   @brief   AUTOSAR Can_43_LLCE - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CAN_LLCE
*   @{
*   Project              : RTD AUTOSAR 4.4
*   Platform             : CORTEXM
*   Peripheral           : LLCE
*   Dependencies         : 
*
*   Autosar Version      : 4.4.0
*   Autosar Revision     : ASR_REL_4_4_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 1.0.7
*   Build Version        : S32_RTD_1_0_7_D2909_ASR_REL_4_4_REV_0000_20230630
*
*   Copyright 2020-2023 NXP Semiconductors
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/*
@brief   (CAN023) The consistency of the configuration must be checked by the configuration tool(s).
@brief   (CAN022) The code configurator of the Can module is CAN controller specific.
         If the CAN controller is sited on-chip, the code generation tool for the Can module is Controller specific.
         If the CAN controller is an external device the generation tool must not be Controller specific.
@brief   (CAN024) The valid values that can be configured are hardware dependent.
         Therefore the rules and constraints can't be given in the standard.
         The configuration tool is responsible to do a static configuration checking, also regarding dependencies between modules (i.e. Port driver, MCU driver etc.)
*/
/*
* @file    Can_43_LLCE_Cfg.h
*/

#ifndef CAN_43_LLCE_CFG_H
#define CAN_43_LLCE_CFG_H

#ifdef __cplusplus
extern "C"{
#endif


/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
#include "Std_Types.h"
#include "Soc_Ips.h"
#include "OsIf.h"

[!AUTOSPACING!]
[!INDENT "0"!]
[!IF "var:defined('postBuildVariant')"!]
    [!LOOP "variant:all()"!]
        #include "Can_43_LLCE_[!"."!]_PBcfg.h"
    [!ENDLOOP!]
[!ELSE!]
    #include "Can_43_LLCE_PBcfg.h"
[!ENDIF!]

[!NOCODE!][!//
[!INCLUDE "Can_43_LLCE_VersionCheck_Inc.m"!][!//
[!ENDNOCODE!][!//

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/*
* @file           Can_43_LLCE_Cfg.h
*/
#define CAN_43_LLCE_VENDOR_ID_CFG_H                     43
#define CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_CFG_H      4
#define CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_CFG_H      4
#define CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_CFG_H   0
#define CAN_43_LLCE_SW_MAJOR_VERSION_CFG_H              1
#define CAN_43_LLCE_SW_MINOR_VERSION_CFG_H              0
#define CAN_43_LLCE_SW_PATCH_VERSION_CFG_H              7

#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
    /* Check if header file and Std_Types.h file are of the same Autosar version */
    #if ((CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_CFG_H != STD_AR_RELEASE_MAJOR_VERSION) || \
         (CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_CFG_H != STD_AR_RELEASE_MINOR_VERSION)    \
        )
        #error "AutoSar Version Numbers of Can_43_LLCE_Cfg.h and Std_Types.h are different"
    #endif

#endif

[!IF "var:defined('postBuildVariant')"!]
    [!LOOP "variant:all()"!]
        /* Check if source file and CAN_43_LLCE_.h configuration header file are of the same vendor */
        #if (CAN_43_LLCE_VENDOR_ID_[!"."!]_PBCFG_H != CAN_43_LLCE_VENDOR_ID_CFG_H)
            #error "CAN_43_LLCE_[!"."!]_PBcfg.h and CAN_43_LLCE_Cfg.h have different vendor IDs"
        #endif
         /* Check if header file and CAN_43_LLCE_.h configuration header file are of the same Autosar version */
        #if ((CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
         (CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_CFG_H) || \
         (CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_CFG_H))
        #error "AutoSar Version Numbers of CAN_43_LLCE_[!"."!]_PBcfg.h and CAN_43_LLCE_Cfg.h are different"
        #endif
        /* Check if header file and CAN_43_LLCE_.h configuration header file are of the same software version */
        #if ((CAN_43_LLCE_SW_MAJOR_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_SW_MAJOR_VERSION_CFG_H) || \
         (CAN_43_LLCE_SW_MINOR_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_SW_MINOR_VERSION_CFG_H) || \
         (CAN_43_LLCE_SW_PATCH_VERSION_[!"."!]_PBCFG_H != CAN_43_LLCE_SW_PATCH_VERSION_CFG_H))
        #error "Software Version Numbers of CAN_43_LLCE_[!"."!]_PBcfg.h and CAN_43_LLCE_Cfg.h are different"
        #endif
    [!ENDLOOP!]
[!ELSE!]
    /* Check if source file and CAN_43_LLCE_.h configuration header file are of the same vendor */
    #if (CAN_43_LLCE_VENDOR_ID_PBCFG_H != CAN_43_LLCE_VENDOR_ID_CFG_H)
     #error "CAN_43_LLCE_PBcfg.h and CAN_43_LLCE_Cfg.h have different vendor IDs"
    #endif
     /* Check if header file and CAN_43_LLCE_.h configuration header file are of the same Autosar version */
    #if ((CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_PBCFG_H != CAN_43_LLCE_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
     (CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_PBCFG_H != CAN_43_LLCE_AR_RELEASE_MINOR_VERSION_CFG_H) || \
     (CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_PBCFG_H != CAN_43_LLCE_AR_RELEASE_REVISION_VERSION_CFG_H))
    #error "AutoSar Version Numbers of CAN_43_LLCE_PBcfg.h and CAN_43_LLCE_Cfg.h are different"
    #endif
    /* Check if header file and CAN_43_LLCE_.h configuration header file are of the same software version */
    #if ((CAN_43_LLCE_SW_MAJOR_VERSION_PBCFG_H != CAN_43_LLCE_SW_MAJOR_VERSION_CFG_H) || \
     (CAN_43_LLCE_SW_MINOR_VERSION_PBCFG_H != CAN_43_LLCE_SW_MINOR_VERSION_CFG_H) || \
     (CAN_43_LLCE_SW_PATCH_VERSION_PBCFG_H != CAN_43_LLCE_SW_PATCH_VERSION_CFG_H))
    #error "Software Version Numbers of CAN_43_LLCE_PBcfg.h and CAN_43_LLCE_Cfg.h are different"
    #endif
[!ENDIF!]


/*==================================================================================================
*                                          CONSTANTS
==================================================================================================*/
/**
* @brief          Enable support for MAC generation and verification.
* @details        Enable support for MAC generation and verification.
*
*/
[!// Loop on all Configuration Sets
[!SELECT "CanConfigSet"!][!//
    [!VAR "MAC_SUPPORT" = "num:i(0)"!][!//
    [!LOOP "node:order(CanHardwareObject/*,'node:value(CanObjectId)')"!][!//
    [!IF "CanObjectType = 'TRANSMIT'"!][!//
        [!IF "CanTxAddFrameMac = 'true'"!][!//
            [!VAR "MAC_SUPPORT"="$MAC_SUPPORT + 1"!][!//
        [!ENDIF!][!//
    [!ELSE!] [!// Receive object
        [!IF "node:exists(CanAdvancedFeature/CanAdvancedFeatureRef) and node:ref(CanAdvancedFeature/CanAdvancedFeatureRef)/AuthenticationFrameEnable = 'true'"!][!//
        [!VAR "MAC_SUPPORT"="$MAC_SUPPORT + 1"!]
        [!ENDIF!][!//
    [!ENDIF!][!//
    [!ENDLOOP!][!//
[!IF "num:i($MAC_SUPPORT) > 0"!][!//
#define CAN_43_LLCE_HSE_SUPPORT_ENABLE    (STD_ON)
[!ELSE!]
#define CAN_43_LLCE_HSE_SUPPORT_ENABLE    (STD_OFF)
[!ENDIF!]


[!VAR "AUX_FILTERS_COUNT" = "num:i(count(CanAuxFilter/*))"!]
[!VAR "GenerateCanAuxFilter" = "'false'"!]
[!IF "node:exists(../CanGeneral/CanAuxFilterEnable)"!]
    [!IF "($AUX_FILTERS_COUNT != num:i(0)) and (node:value(../CanGeneral/CanAuxFilterEnable) = 'true')"!]
        [!VAR "GenerateCanAuxFilter"="'true'"!]
    [!ENDIF!]
[!ENDIF!]

[!IF "$GenerateCanAuxFilter = 'true'"!]
#define RXLUT2_ENABLE  (STD_ON)
[!ELSE!]
#define RXLUT2_ENABLE  (STD_OFF) 
[!ENDIF!]
[!ENDSELECT!]




/**
* @brief          Implicit index value used by Full can hardware objects.
* @details        Implicit index value used by Full can hardware objects.
*
*/
#define CAN_43_LLCE_MAX_IDMASK    (Can_IdType)0x1FFFFFFFU

[!NOCODE!]
[!// Loop on all Configuration Sets
[!SELECT "CanConfigSet"!][!//
    [!VAR "ConfigSetIndex" = "0"!][!//
    [!LOOP "CanController/*"!][!//
    [!// Loop on all channels inside the same Configuration Set
        [!VAR "SavedIndex" = "CanControllerId"!][!//
        [!VAR "Name" = "@name"!][!//
        [!// Loop on all other Configuration Sets
        [!LOOP "../../../*[@index>$ConfigSetIndex]/CanController/*"!][!//
            [!IF "($Name = node:name(.))"!][!//
                [!IF "($SavedIndex != CanControllerId)"!][!//
                    [!// Error
                    [!ERROR!][!//
                        [!"$Name"!][!"'- Symbolic name for controller Ids can be repeated only if they have the same CanControllerId in each of the config set.'"!][!//
                    [!ENDERROR!][!//
                [!ENDIF!][!//
            [!ENDIF!][!//
        [!ENDLOOP!][!//     
    [!ENDLOOP!][!//
[!ENDSELECT!]
[!/* Check status of CanHwFilter and CanMainFunctionRWPeriodRef */!]
[!SELECT "CanConfigSet"!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "((((CanObjectType = 'TRANSMIT') and ((node:ref(CanControllerRef))/CanTxProcessing) = 'POLLING')  or
                ((CanObjectType = 'RECEIVE' ) and ((node:ref(CanControllerRef))/CanRxProcessing) = 'POLLING'))
                   and (not(node:refexists(CanMainFunctionRWPeriodRef))))"!]
            [!ERROR!]
            The "CanMainFunctionRWPeriodRef" must be enabled when user configure the Can controller operate in the Polling mode (both to transmission and reception)
            [!ENDERROR!]
        [!ENDIF!]
        [!IF "((CanObjectType = 'RECEIVE')) and (not(node:exists(CanHwFilter)))"!]
            [!ERROR!]
            The "CanHwFilter" of each HOH must be enabled when user configure HOH is receive.
            [!ENDERROR!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDNOCODE!]
[!/* Check if two controllers have the same name in any ConfigSet */!]
[!VAR "OuterLoopCounter" = "0"!][!VAR "InnerLoopCounter" = "0"!]
[!LOOP "CanConfigSet/CanController/*"!]
    [!VAR "OuterLoopCounter" = "$OuterLoopCounter + 1"!]
    [!VAR "InnerLoopCounter" = "0"!]
    [!VAR "Matchcounter" = "0"!]
    [!VAR "Name" = "node:name(.)"!]
    [!LOOP "../../CanController/*"!]
        [!VAR "InnerLoopCounter" = "$InnerLoopCounter + 1"!]
        [!IF "$OuterLoopCounter >= $InnerLoopCounter"!]
            [!IF "($Name = node:name(.))"!]
                [!VAR "Matchcounter" = "$Matchcounter + 1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$Matchcounter != 1"!]
        [!WARNING!] Some controllers have identical name. Should avoid this because of multiple generated DEFINEs with the same name![!ENDWARNING!]
    [!ENDIF!]
[!ENDLOOP!]

[!NOCODE!][!//
// Loop on all Configuration Sets to check if the symbolic names are duplicated between config sets
[!SELECT "CanConfigSet"!][!//
    [!VAR "ConfigSetIndex" = "0"!][!//
    // Loop on all channels inside the same Configuration Set
    [!LOOP "CanHardwareObject/*"!][!//
    [!VAR "SavedIndex" = "CanObjectId"!][!//
        [!VAR "Name" = "@name"!][!//
        // Loop on all other Configuration Sets
        [!LOOP "../../../*[@index>$ConfigSetIndex]/CanHardwareObject/*"!][!//
            [!IF "($Name = node:name(.))"!][!//
                [!IF "($SavedIndex != CanObjectId)"!][!//
                    // Error
                    [!ERROR!][!//
                        [!"$Name"!][!"'- Symbolic name for hardware object Ids can be repeated only if they have the same value for CanObjectId in each of the config set.'"!][!//
                    [!ENDERROR!][!//
                [!ENDIF!][!//
            [!ENDIF!][!//
        [!ENDLOOP!][!//     
    [!ENDLOOP!][!//
[!ENDSELECT!]
 
[!VAR "OuterLoopCounter" = "0"!][!VAR "InnerLoopCounter" = "0"!]
[!LOOP "CanConfigSet/CanHardwareObject/*"!]
    [!VAR "OuterLoopCounter" = "$OuterLoopCounter + 1"!]
    [!VAR "InnerLoopCounter" = "0"!]
    [!VAR "Matchcounter" = "0"!]
    [!VAR "Name" = "node:name(.)"!]
    [!LOOP "../../CanHardwareObject/*"!]
        [!VAR "InnerLoopCounter" = "$InnerLoopCounter + 1"!]
        [!IF "$OuterLoopCounter >= $InnerLoopCounter"!]
            [!IF "($Name = node:name(.))"!]
                [!VAR "Matchcounter" = "$Matchcounter + 1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$Matchcounter != 1"!]
        [!WARNING!] Some MBs have identical name. Should avoid this because of multiple generated DEFINEs with the same name![!ENDWARNING!]
    [!ENDIF!]
[!ENDLOOP!]

[!SELECT "CanConfigSet"!]
    [!VAR "MaxObjectIdForReceiveHO" = "-1"!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'RECEIVE'"!]
            [!IF "$MaxObjectIdForReceiveHO < CanObjectId"!]
                [!VAR "MaxObjectIdForReceiveHO" = "CanObjectId"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
    [!LOOP "CanHardwareObject/*"!]
        [!IF "CanObjectType = 'TRANSMIT'"!]
            [!IF "$MaxObjectIdForReceiveHO >= CanObjectId"!]
                [!ERROR!]
                The HRH and HTH Ids are defined under two different name-spaces (Refer to CAN326).
                Example: HRH0-0, HRH1-1, HTH0-2, HTH1-3.
                The HRHs of all controllers are grouped before the HTHs of all controllers
                    (there must not be any HTH of any controller with an object ID lower than
                    that of any HRH configured for this driver).
                [!ENDERROR!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDNOCODE!]


/*
* @brief          Symbolic names for CanObjectId
* @details        Symbolic names for CanObjectId maintained for compatibility with old testcases/applications 
*
*/
[!SELECT "CanConfigSet"!][!//
 [!LOOP "CanHardwareObject/*"!]
    [!IF "CanObjectType = 'RECEIVE'"!]
        #define [!WS "1"!][!"@name"!] [!WS "1"!][!"num:i(CanObjectId)"!]U /* RECEIVE object of Can Controller ID = [!"num:i(node:ref(CanControllerRef)/CanControllerId)"!] */
    [!ENDIF!]
[!ENDLOOP!]
[!ENDSELECT!]
[!SELECT "CanConfigSet"!][!//
[!LOOP "CanHardwareObject/*"!]
    [!IF "CanObjectType = 'TRANSMIT'"!]
        #define [!WS "1"!][!"@name"!] [!WS "1"!][!"num:i(CanObjectId)"!]U /* TRANSMIT object of Can Controller ID = [!"num:i(node:ref(CanControllerRef)/CanControllerId)"!] */
    [!ENDIF!]
[!ENDLOOP!]
[!ENDSELECT!]

/*
* @brief          Lpdu callout name
* @details        (CAN357_Conf) CanLPduReceiveCalloutFunction - This parameter sets the name of the LPDU callout.
*
*/
[!IF "node:exists(CanGeneral/CanLPduReceiveCalloutFunction) and (normalize-space(CanGeneral/CanLPduReceiveCalloutFunction) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_LPDU_NOTIFICATION_ENABLE  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_LPDU_NOTIFICATION_ENABLE  (STD_OFF)
[!ENDIF!]

#define CAN_43_LLCE_LPDU_CALLOUT_EXTENSION [!WS "1"!][!IF "((node:exists(CanGeneral/LPDUCalloutExtension)) and (CanGeneral/LPDUCalloutExtension ='true'))"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Callout function name for timestamp of received frames
*
*/
[!IF "node:exists(CanGeneral/RxTimestampNotification) and (normalize-space(CanGeneral/RxTimestampNotification) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_RX_TIMESTAMP  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_RX_TIMESTAMP  (STD_OFF)
[!ENDIF!]

/*
* @brief          Callout function name for timestamp of frame confirmations
*
*/
[!IF "node:exists(CanGeneral/TxTimestampNotification) and (normalize-space(CanGeneral/TxTimestampNotification) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_ACK_TIMESTAMP  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_ACK_TIMESTAMP  (STD_OFF)
[!ENDIF!]

/*
* @brief          Callback for frames received through customization filters
*
*/
[!IF "node:exists(CanGeneral/CanCustomRxFunction) and (normalize-space(CanGeneral/CanCustomRxFunction) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_CUSTOM_RX_CALLBACK_USED  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_CUSTOM_RX_CALLBACK_USED  (STD_OFF)
[!ENDIF!]

/*
* @brief          Callback for each frame sent to LLCE firmware through Can_Write
*
*/
[!IF "node:exists(CanGeneral/CanWriteCustomCallback) and (normalize-space(CanGeneral/CanWriteCustomCallback) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_CUSTOM_WRITE_CALLBACK_USED  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_CUSTOM_WRITE_CALLBACK_USED  (STD_OFF)
[!ENDIF!]

/*
* @brief          Callback for each TX Confirmation received from LLCE firmware.
*
*/
[!IF "node:exists(CanGeneral/CanTxConfirmationCustomCallback) and (normalize-space(CanGeneral/CanTxConfirmationCustomCallback) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_CUSTOM_CONFIRMATION_CALLBACK  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_CUSTOM_CONFIRMATION_CALLBACK  (STD_OFF)
[!ENDIF!]


/*
* @brief          Callout function name for reporting errors.
*
*/
[!IF "node:exists(CanConfigSet/CanErrorReporting/CanErrorNotif) and (normalize-space(CanConfigSet/CanErrorReporting/CanErrorNotif) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_ERROR_NOTIF_ENABLE  (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_ERROR_NOTIF_ENABLE  (STD_OFF)
[!ENDIF!]

/*
* @brief          Extended identifiers.
* @details        Extended identifiers.
                   - (STD_ON)  - if at least one extended identifier is used.
                   - (STD_OFF) - if no extended identifiers are used at all
                  If no extended identifiers are used then the IDs and MASKs can be stored in uint16 rather than uint32.
*
*/

#define CAN_43_LLCE_SET_BAUDRATE_API [!WS "1"!][!IF "((node:exists(CanGeneral/CanSetBaudrateApi)) and (CanGeneral/CanSetBaudrateApi ='true'))"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

#define CAN_LLCE_USE_HEADLESSMODE [!WS "1"!][!IF "((node:exists(CanGeneral/CanLlceEnableHeadlessMode)) and (CanGeneral/CanLlceEnableHeadlessMode ='true'))"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]
/*
* @brief          Switches the Development Error Detection and Notification ON or OFF.
* @details        (CAN028) Call the Development Error Tracer when DET is switched on and the Can module detects an error.
                  (CAN082) The detection of development errors is configurable (ON / OFF) at pre- compile time.
                  The switch CanDevErrorDetect (see chapter 10) shall activate or deactivate the detection of all development errors.
*
*/
#define CAN_43_LLCE_DEV_ERROR_DETECT [!WS "1"!][!IF "CanGeneral/CanDevErrorDetect = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Switches between user mode and supervisor mode.
* @details        Switches between user mode and supervisor mode. Some peripherals, eg. sema42 require supervisor mode.
*
*/

[!IF "CanGeneral/CanEnableUserModeSupport = 'true'"!]
#ifndef MCAL_ENABLE_USER_MODE_SUPPORT
#error MCAL_ENABLE_USER_MODE_SUPPORT must be defined when driver is configured in user mode
#endif
#define CAN_LLCE_ENABLE_USER_MODE_SUPPORT
[!ENDIF!]

/*
* @brief          Support for version info API
* @details        Switches the Can_43_LLCE_GetVersionInfo() API ON or OFF.
*
*/
#define CAN_43_LLCE_VERSION_INFO_API [!WS "1"!][!IF "CanGeneral/CanVersionInfoApi = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/*
* @brief          Instance # of the driver - used for Det_ReportError().
* @details        Instance # of the driver - used for Det_ReportError().
*
*/
#define CAN_43_LLCE_INSTANCE [!WS "1"!][!"num:i(CanGeneral/CanIndex)"!]U

/*
* @brief          Enables the reporting to AUTOSAR modules. (e.g. CanIf, Det)
* @details        It's used for compatibility with DS, which can operate in non-ASR mode. 
*
*/
#ifndef AUTOSAR_COMPATIBLE_MODE
#define AUTOSAR_COMPATIBLE_MODE   (STD_ON)
#endif


    
/**
*   @brief      The definition used for guarding GetCoreID/Multicore
*/
#define CAN_43_LLCE_MULTICORE_ENABLED[!WS "4"!][!IF "num:i(count(CanGeneral/CanEcucPartitionRef/*)) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      The definition represent for number of ECUC partition configured.
*/
[!NOCODE!]
    [!VAR "maxCoreDefConfig" = "num:i(1)"!]
    [!IF "CanGeneral/CanMulticoreSupport = 'true'"!]
        [!IF "node:exists(as:modconf('EcuC')[1]/EcucHardware/*/EcucCoreDefinition)"!]
            [!VAR "maxCoreDefConfig" = "num:i(count(as:modconf('EcuC')[1]/EcucHardware/*/EcucCoreDefinition/*))"!]
        [!ENDIF!]
    [!ENDIF!]
[!ENDNOCODE!]
#define CAN_43_LLCE_MAX_PARTITIONS[!WS "4"!][!"$maxCoreDefConfig"!]U

/*
* @brief          The define in order to check the trigger transmit feature is enabled or disabled.
* @details        The define in order to check the trigger transmit feature is enabled or disabled.
*
*/
[!IF "num:i(count(CanConfigSet/CanHardwareObject/*[CanTriggerTransmitEnable = 'true'])) > 0"!]
    #define CAN_43_LLCE_TRIGGER_TRANSMIT_EN (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_TRIGGER_TRANSMIT_EN (STD_OFF)
[!ENDIF!]

/*
* @brief          The define in order to check the dummy hrh feature is enabled or disabled.
* @details        The define in order to check the dummy hrh transmit feature is enabled or disabled.
*
*/
[!IF "num:i(count(CanConfigSet/CanHardwareObject/*[Dummy_HRH = 'true'])) > 0"!]
    #define CAN_43_LLCE_DUMMY_HRH_EN (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_DUMMY_HRH_EN (STD_OFF)
[!ENDIF!]

/*123 Calculate the maximum number of HRH and HTH amd MBs from all config sets */
[!SELECT "CanConfigSet"!]
    [!VAR "HrhCount"="0"!]
    [!VAR "HthCount"="0"!]
    [!VAR "RxMbCount"="0"!]
    [!VAR "TxMbCount"="0"!]
    [!VAR "Can_First_HTH_Index" = "0"!]
    [!VAR "Can_Check_ExistHTH" = "0"!]
    [!LOOP "node:order(CanHardwareObject/*,'node:value(CanObjectId)')"!]  
        [!IF "CanObjectType = 'RECEIVE'"!]
            [!VAR "HrhCount"="$HrhCount + 1"!]  
            [!IF "node:exists(CanHwObjectCount)"!]
                [!VAR "RxMbCount"="$RxMbCount + node:value(CanHwObjectCount)"!] 
            [!ELSE!]
                [!VAR "RxMbCount"="$RxMbCount + 1"!] 
            [!ENDIF!]                
        [!ELSE!]
            [!VAR "HthCount"="$HthCount + 1"!] 
            [!IF "node:exists(CanHwObjectCount)"!]
                [!VAR "TxMbCount"="$TxMbCount + node:value(CanHwObjectCount)"!] 
            [!ELSE!]
                [!VAR "TxMbCount"="$TxMbCount + 1"!] 
            [!ENDIF!] 
            [!IF "$Can_Check_ExistHTH = 0"!]
                [!VAR "Can_First_HTH_Index" = "CanObjectId"!]
                [!VAR "Can_Check_ExistHTH" = "1"!]
            [!ENDIF!]
        [!ENDIF!]
    [!ENDLOOP!]

/*
* @brief          Maximum number of HRHs configured.
*
*/
#define CAN_43_LLCE_MAXHRH_CONFIGURED [!WS "1"!]
        [!IF "num:i($HrhCount) > 0"!]
             [!"num:i($HrhCount)"!]U
        [!ELSE!]
             1U
        [!ENDIF!] 

 /*
* @brief          Maximum number of HTHs configured.
*
*/       
#define CAN_43_LLCE_MAXHTH_CONFIGURED [!WS "1"!]
        [!IF "num:i($HthCount) > 0"!]
             [!"num:i($HthCount)"!]U
        [!ELSE!]
             1U
        [!ENDIF!] 

 /*
* @brief          Maximum number of HOHs configured.
*
*/       
#define CAN_43_LLCE_MAXHOH_CONFIGURED [!WS "1"!]
        (CAN_43_LLCE_MAXHRH_CONFIGURED [!WS "1"!] + CAN_43_LLCE_MAXHTH_CONFIGURED [!WS "1"!])

/*
* @brief          The index of the first HTH configured
*
*/  
#define CAN_43_LLCE_FIRST_HTH_CONFIGURED [!WS "1"!]
        [!IF "$Can_Check_ExistHTH = 0"!][!/* Unless it has any HTH, Can_First_HTH_Index will be equal Max MB count  */!]
            [!"num:i($HrhCount + $HthCount)"!]U
        [!ELSE!]
            [!"num:i($Can_First_HTH_Index)"!]U
        [!ENDIF!]

/*
* @brief          Maximum number of RXMBs configured.
*
*/  
#define CAN_43_LLCE_MAXRXMB_CONFIGURED [!WS "1"!]
    [!IF "num:i($RxMbCount) > 0"!]
        [!"num:i($RxMbCount)"!]U
    [!ELSE!]
        1U
    [!ENDIF!]

/*
* @brief          Maximum number of TXMBs configured.
*
*/ 
#define CAN_43_LLCE_MAXTXMB_CONFIGURED [!WS "1"!]
    [!IF "num:i($TxMbCount) > 0"!]
        [!"num:i($TxMbCount)"!]U
    [!ELSE!]
        1U
    [!ENDIF!] 
[!ENDSELECT!]


/*
* @brief          Maximum No. of controllers Configured
* @details      Maximum No. of controllers Configured
*
*/
[!NOCODE!]
[!VAR "ctrl_no" = "0"!]
[!SELECT "CanConfigSet"!]
    [!VAR "ctrl_no" = "num:i(count(CanController/*))"!] 
[!ENDSELECT!]
[!ENDNOCODE!]
#define CAN_43_LLCE_MAXCTRL_CONFIGURED [!WS "1"!][!"$ctrl_no"!]U

/**
* @brief          Hardware events detected by an interrupt or by polling
* @details        (CAN099) The hardware events may be detected by an interrupt or by polling status flags of the hardware objects.
*                 The configuration possibilities regarding polling is hardware dependent (i.e. which events can be polled, which events need to be polled), and not restricted by this standard.
*                 (CAN007)It shall be possible to configure the driver such that no interrupts at all are used (complete polling).
*
*/
[!NOCODE!]
[!VAR "tx_pol_en"="0"!]
[!SELECT "CanConfigSet"!]
    [!LOOP "CanController/*"!]
        [!IF "CanTxProcessing = 'POLLING'"!]
            [!VAR "tx_pol_en" = "1"!]
            [!BREAK!]  
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$tx_pol_en = 0"!]
        [!LOOP "node:order(CanHardwareObject/*,'node:value(CanObjectId)')"!]
            [!IF "CanObjectType = 'TRANSMIT' and node:ref(CanControllerRef)/CanTxProcessing = 'MIXED' and CanHardwareObjectUsesPolling = 'true'"!]
                [!VAR "tx_pol_en" = "1"!]
                [!BREAK!]  
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDIF!]
[!ENDSELECT!]
[!ENDNOCODE!]

/*
* @brief          This macro enables Can_43_LLCE_MainFunction_Write() if at least one controller is set to process Tx in Polling Mode.
* @details        This macro enables Can_43_LLCE_MainFunction_Write() if at least one controller is set to process Tx in Polling Mode.
*
*/
#define CAN_43_LLCE_TXPOLL_SUPPORTED   [!IF "$tx_pol_en = 1"!][!WS "1"!](STD_ON)[!ELSE!][!WS "1"!](STD_OFF)[!ENDIF!]

[!NOCODE!]
[!VAR "rx_pol_en"="0"!]
[!SELECT "CanConfigSet"!]
    [!LOOP "CanController/*"!]
        [!IF "CanRxProcessing = 'POLLING'"!]
            [!VAR "rx_pol_en" = "1"!]
            [!BREAK!]  
        [!ENDIF!]
    [!ENDLOOP!]
    [!IF "$rx_pol_en = 0"!]
        [!LOOP "node:order(CanHardwareObject/*,'node:value(CanObjectId)')"!]
            [!IF "CanObjectType = 'RECEIVE' and node:ref(CanControllerRef)/CanRxProcessing = 'MIXED' and CanHardwareObjectUsesPolling = 'true'"!]
                [!VAR "rx_pol_en" = "1"!]
                [!BREAK!]  
            [!ENDIF!]
        [!ENDLOOP!]
    [!ENDIF!]
[!ENDSELECT!]
[!ENDNOCODE!]

/*
* @brief          This macro enables Can_43_LLCE_MainFunction_Read() if at least one controller is set to process Rx in Polling Mode.
* @details        This macro enables Can_43_LLCE_MainFunction_Read() if at least one controller is set to process Rx in Polling Mode.
*
*/
#define CAN_43_LLCE_RXPOLL_SUPPORTED   [!IF "$rx_pol_en = 1"!][!WS "1"!](STD_ON)[!ELSE!][!WS "1"!](STD_OFF)[!ENDIF!][!CR!]


[!NOCODE!]
[!VAR "bo_pol_en"="0"!]
[!SELECT "CanConfigSet"!][!//
    [!LOOP "CanController/*"!]
        [!IF "CanBusoffProcessing = 'POLLING'"!]
            [!VAR "bo_pol_en" = "1"!]
            [!BREAK!]  
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDSELECT!]
[!ENDNOCODE!]


/*
* @brief          This macro enables Can_43_LLCE_MainFunction_BusOff() if at least one controller is set to process BusOff in Polling Mode.
* @details        This macro enables Can_43_LLCE_MainFunction_BusOff() if at least one controller is set to process BusOff in Polling Mode.
*
*/
#define CAN_43_LLCE_BUSOFFPOLL_SUPPORTED   [!IF "$bo_pol_en = 1"!][!WS "1"!](STD_ON)[!ELSE!][!WS "1"!](STD_OFF)[!ENDIF!][!CR!]


/*
* @brief          This macro enables Can_43_LLCE_MainFunction_ErrorNotification() and is used for reporting errors configured in Polling Mode.
*
*/
[!SELECT "CanConfigSet"!]
[!SELECT "CanErrorReporting"!]
#define CAN_43_LLCE_ERRORNOTIFPOLL_SUPPORTED   [!IF "CanMainFunctionErrorEn = 'true'"!][!WS "1"!](STD_ON)[!ELSE!][!WS "1"!](STD_OFF)[!ENDIF!][!CR!]
[!ENDSELECT!]
[!ENDSELECT!]


/**
* @brief          Maximum number of baudrate configured.
* @details        Maximum number of baudrate configured.
*                 Controller Baudrates configured are in kbps
*
*/
[!SELECT "CanConfigSet"!][!//
    [!LOOP "CanController/*"!]
        [!VAR "HWChannel" = "CanHwChannel"!]
        #define CAN_43_LLCE_MAX_BAUDRATE_FC_[!"substring-after($HWChannel,'BCAN_')"!]_[!"@index"!]   [!WS "1"!][!"num:i(count(CanControllerBaudrateConfig/*))"!]U[!CR!]
    [!ENDLOOP!]
[!ENDSELECT!]

/* CAN FD INIT*/
[!NOCODE!]
[!VAR "CNT_FD" = "0"!]
[!SELECT "CanConfigSet"!][!//
    [!IF "node:exists(CanController/*/CanControllerBaudrateConfig/*/CanControllerFdBaudrateConfig)"!]
        [!VAR "CNT_FD" = "$CNT_FD+1"!] 
    [!ENDIF!]
[!ENDSELECT!]
[!ENDNOCODE!]
[!IF "$CNT_FD > 0"!]
    #define CAN_43_LLCE_FD_MODE_ENABLE (STD_ON)
    [!VAR "CNT_FD" = "0"!]
[!ELSE!]
    #define CAN_43_LLCE_FD_MODE_ENABLE (STD_OFF)
[!ENDIF!]

[!SELECT "CanGeneral"!]
/*
* @brief          (CAN113_Conf) Specifies the maximum time for blocking function until a timeout is detected. Unit in loops.
* @details        (CAN281) The Can module shall use the free running timer provided by the system service for timeout detection in case the hardware does not react
*                  in the expected time (hardware malfunction) to prevent endless loops.
*
*/
/* Time out value in uS */
#define CAN_43_LLCE_TIMEOUT_DURATION    [!"num:i(./CanTimeoutDuration * 1000000)"!]U

/* This will set the timer source for osif that will be used for timeout */
#define CAN_43_LLCE_SERVICE_TIMEOUT_TYPE    [!"CanTimeoutMethod"!]

[!ENDSELECT!]


/*
* @brief          Precompile Support.
* @details        (CAN220)VARIANT-PRE-COMPILE: Only pre-compile configuration parameters
*
*/
[!IF "IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile' and (variant:size()<=1)"!]
    #define CAN_43_LLCE_PRECOMPILE_SUPPORT (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_PRECOMPILE_SUPPORT (STD_OFF)
[!ENDIF!]

[!IF "node:exists(CanGeneral/CanMainFunctionBusoffPeriod)"!]
    /*
    * @brief          Periods for cyclic call of Main function
    * @details        (CAN355_Conf) CanMainFunctionBusoffPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Busoff. Unit is seconds.
    *
    */
    #define CAN_43_LLCE_MAINFUNCTION_PERIOD_BUSOFF  [!WS "1"!][!SELECT "CanGeneral"!]([!"./CanMainFunctionBusoffPeriod"!]F)[!ENDSELECT!][!CR!]
[!ENDIF!]


/*
* @brief          Periods for cyclic call of Main function
* @details        (ECUC_Can_00484) This parameter describes the period for cyclic call to Can_43_LLCE_MainFunction_Read or Can_43_LLCE_MainFunction_Write depending on the referring item. Unit is seconds. 
*                 Different poll-cycles will be configurable if more than one CanMainFunctionPeriod is configured. 
*                 In this case multiple Can_43_LLCE_MainFunction_Read() or Can_43_LLCE_MainFunction_Write() will be provided by the CAN Driver module..
*
*/
[!VAR "MainFuncPeriodCount" = "num:i(count(CanGeneral/CanMainFunctionRWPeriods/*))"!]

[!IF "$MainFuncPeriodCount = 0 or $MainFuncPeriodCount = 1"!]
    #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_READ  (STD_OFF)
    #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_WRITE (STD_OFF)
[!ELSE!]
    [!VAR "MAX_CTRL_COUNT"="16"!]
    [!IF "$rx_pol_en = 1"!]
        #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_READ   (STD_ON)
    [!ELSE!]
        #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_READ  (STD_OFF)
    [!ENDIF!]
    [!IF "$tx_pol_en = 1"!]
        #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_WRITE   (STD_ON)
    [!ELSE!]
        #define CAN_43_LLCE_MAINFUNCTION_MULTIPLE_WRITE  (STD_OFF)
    [!ENDIF!]
    [!LOOP "CanGeneral/CanMainFunctionRWPeriods/*"!]
        [!VAR "rx_hoh_pol_en"="0"!]
        [!VAR "tx_hoh_pol_en"="0"!]
        [!VAR "CanMainFunctionPeriodName" = "@name"!]
        [!LOOP "../../../CanConfigSet/CanHardwareObject/*"!]
            [!IF "($rx_hoh_pol_en = 0) and ((node:ref(CanControllerRef)/CanRxProcessing = 'POLLING' or (node:ref(CanControllerRef)/CanRxProcessing = 'MIXED' and CanHardwareObjectUsesPolling = 'true')) and (CanObjectType = 'RECEIVE')) and ($CanMainFunctionPeriodName = node:ref(CanMainFunctionRWPeriodRef)/@name)"!]
                [!VAR "rx_hoh_pol_en" = "1"!]
            [!ENDIF!]
            [!IF "($tx_hoh_pol_en = 0) and ((node:ref(CanControllerRef)/CanTxProcessing = 'POLLING' or (node:ref(CanControllerRef)/CanTxProcessing = 'MIXED' and CanHardwareObjectUsesPolling = 'true')) and (CanObjectType = 'TRANSMIT')) and ($CanMainFunctionPeriodName = node:ref(CanMainFunctionRWPeriodRef)/@name)"!]
                [!VAR "tx_hoh_pol_en" = "1"!]    
            [!ENDIF!]
            [!IF "($rx_hoh_pol_en = 1) and ($tx_hoh_pol_en = 1)"!]
                [!BREAK!]    
            [!ENDIF!]
        [!ENDLOOP!]
        [!IF "$rx_hoh_pol_en = 1"!]
            #define Can_43_LLCE_MainFunction_Read_[!"@name"!]()       Can_43_LLCE_MainFunction_Multiple_Read([!"num:i(RxInterface - $MAX_CTRL_COUNT)"!]) [!// RxInterface translates into polling class by subtracting 16
        [!ENDIF!]
        [!IF "$tx_hoh_pol_en = 1"!]
            #define Can_43_LLCE_MainFunction_Write_[!"@name"!]()       Can_43_LLCE_MainFunction_Multiple_Write([!"num:i(AckInterface - $MAX_CTRL_COUNT)"!]) [!// AckInterface translates into polling class by subtracting 16
        [!ENDIF!]
    [!ENDLOOP!]
[!ENDIF!]


/*
* @brief          Periods for cyclic call of Main function Mode
* @details        (CAN376_Conf) This parameter describes the period for cyclic call to Can_43_LLCE_MainFunction_Mode. Unit is seconds.
*
*/
#define CAN_43_LLCE_MAINFUNCTION_MODE_PERIOD   [!WS "1"!][!SELECT "CanGeneral"!]([!"./CanMainFunctionModePeriod"!]F)[!ENDSELECT!]


/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
#define CAN_43_LLCE_CONFIG_EXT \
    [!INDENT "4"!]
    [!IF "var:defined('postBuildVariant') or (variant:size() > 1)"!]
        [!VAR "variantIndex"="0"!]
        [!VAR "variantNumber"="variant:size()"!]
        [!LOOP "variant:all()"!]
            [!VAR "variantIndex"="$variantIndex + 1"!]
            CAN_43_LLCE_CONFIG_[!"."!]_PB [!IF "$variantIndex < $variantNumber"!]\[!ENDIF!][!CR!]
        [!ENDLOOP!]
    [!ELSE!]
        CAN_43_LLCE_CONFIG_PB
    [!ENDIF!]
    [!ENDINDENT!]

/*
* @brief          Support for Special MB Abort API
* @details        Enables an additional API which adds support for aborting a message transmission.
*/
#define CAN_43_LLCE_API_ENABLE_ABORT_MB [!WS "1"!][!IF "(CanGeneral/CanApiEnableMbAbort = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/*
* @brief          Support for single MB Abort  API
* @details        Extra information for AbortMB API which selects between single MB abort and aborting all the MBs corresponding to a specific HTH.
*/
#define CAN_43_LLCE_ABORT_ONLY_ONE_MB [!WS "1"!][!IF "(CanGeneral/CanAbortOnlyOneMB = 'true') and (CanGeneral/CanApiEnableMbAbort = 'true')"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/*
* @brief          Support for Manual BusOff recovery request API
* @details        Enables an additional API for requesting recovery from BusOff confinement state. 
*                 It is enabled when at least one controller configuration handles the recovery from bus-off manually.
*                 Not Autosar required.
*/
#define CAN_43_LLCE_API_MANUAL_BUSOFF_RECOVERY [!WS "1"!][!VAR "ManualBusOffRec" = "CanConfigSet/CanController/*/ManualBusOffRecovery = 'true'"!] [!// At least one controller has ManualBusOffRecovery enabled
[!IF "$ManualBusOffRec = 'true'"!] (STD_ON)[!ELSE!] (STD_OFF)[!ENDIF!]

/*
* @brief          Checks whether the BUSOFF_RECOVERY mode is ENABLED.
* @details        BUSOFF_RECOVERY is ENABLED when Manual or Auto Bus-off Recovery is set for any controller.
*                 Not Autosar required.
*/
[!SELECT "CanGeneral"!][!IF "node:exists(./BusOffNotification) and (normalize-space(./BusOffNotification) != 'NULL_PTR')"!]
    #define CAN_43_LLCE_BUSOFF_RECOVERY_ENABLED     (STD_ON)
[!ELSE!]
    #define CAN_43_LLCE_BUSOFF_RECOVERY_ENABLED     (STD_OFF)
[!ENDIF!][!ENDSELECT!]

/*==================================================================================================
*                                             ENUMS
==================================================================================================*/

/*==================================================================================================
*                                STRUCTURES AND OTHER TYPEDEFS
==================================================================================================*/

/*==================================================================================================
*                                GLOBAL VARIABLE DECLARATIONS
==================================================================================================*/

/*==================================================================================================
*                                    FUNCTION PROTOTYPES
==================================================================================================*/

[!ENDINDENT!]

#ifdef __cplusplus
}
#endif

#endif /* CAN_43_LLCE_CFG_H */

/** @} */
