/**
*   @file    CanTrcv_43_tja1145a_Cfg.h
*   @version 0.8.0
*
*   @brief   AUTOSAR CanTrcv_43_tja1145a - module interface
*   @details Configuration settings generated by user settings.
*
*   @addtogroup CanTrcv_tja1145a_Driver
*   @{
*/
/*==================================================================================================
*   Project              : RTD AUTOSAR 4.7
*   Platform             : CORTEXM
*   Peripheral           : 
*   Dependencies         : 
*
*   Autosar Version      : 4.7.0
*   Autosar Revision     : ASR_REL_4_7_REV_0000
*   Autosar Conf.Variant :
*   SW Version           : 0.8.0
*   Build Version        : S32K3_RTD_0_8_0_D2305_ASR_REL_4_7_REV_0000_20230524
*
*   (c) Copyright 2020 - 2023 NXP Semiconductors
*   All Rights Reserved.
*
*   NXP Confidential. This software is owned or controlled by NXP and may only be
*   used strictly in accordance with the applicable license terms. By expressly
*   accepting such terms or by downloading, installing, activating and/or otherwise
*   using the software, you are agreeing that you have read, and that you agree to
*   comply with and are bound by, such license terms. If you do not agree to be
*   bound by the applicable license terms, then you may not retain, install,
*   activate or otherwise use the software.
==================================================================================================*/
/*==================================================================================================
==================================================================================================*/
/*
* @file    CanTrcv_43_tja1145a_Cfg.h
*/

#ifndef CANTRCV_43_TJA1145A_CFG_H
#define CANTRCV_43_TJA1145A_CFG_H

#ifdef __cplusplus
extern "C"{
#endif

/*==================================================================================================
*                                        INCLUDE FILES
* 1) system and project includes
* 2) needed interfaces from external units
* 3) internal and external interfaces from this unit
==================================================================================================*/
[!IF "(IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild' or (variant:size()>1))"!] [!//
[!IF "var:defined('postBuildVariant')"!][!//
    [!LOOP "variant:all()"!]
#include "CanTrcv_43_tja1145a_[!"."!]_PBcfg.h"
    [!ENDLOOP!]
[!ELSE!][!//
#include "CanTrcv_43_tja1145a_PBcfg.h"
[!ENDIF!][!//
[!AUTOSPACING!]
[!ENDIF!][!//

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/
#define CANTRCV_43_TJA1145A_VENDOR_ID_CFG_H                     43
#define CANTRCV_43_TJA1145A_MODULE_ID_CFG_H                     70
#define CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_H      4
#define CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_H      7
#define CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_CFG_H   0
#define CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_CFG_H              0
#define CANTRCV_43_TJA1145A_SW_MINOR_VERSION_CFG_H              8
#define CANTRCV_43_TJA1145A_SW_PATCH_VERSION_CFG_H              0

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/
[!IF "(IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild' or (variant:size()>1))"!] [!//
[!IF "var:defined('postBuildVariant')"!][!//
[!LOOP "variant:all()"!]
/* Check if source file and CanTrcv configuration header file are of the same vendor */
#if (CANTRCV_43_TJA1145A_VENDOR_ID_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_VENDOR_ID_CFG_H)
    #error "CanTrcv_43_tja1145a_[!"."!]_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h have different vendor IDs"
#endif
 /* Check if header file and CanTrcv configuration header file are of the same Autosar version */
#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_CFG_H))
    #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_[!"."!]_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h are different"
#endif
/* Check if header file and CanTrcv configuration header file are of the same software version */
#if ((CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_SW_MINOR_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_SW_MINOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_SW_PATCH_VERSION_[!"."!]_PBCFG_H != CANTRCV_43_TJA1145A_SW_PATCH_VERSION_CFG_H))
    #error "Software Version Numbers of CanTrcv_43_tja1145a_[!"."!]_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h are different"
#endif
[!ENDLOOP!]
[!ELSE!][!//
/* Check if source file and CanTrcv configuration header file are of the same vendor */
#if (CANTRCV_43_TJA1145A_VENDOR_ID_PBCFG_H != CANTRCV_43_TJA1145A_VENDOR_ID_CFG_H)
    #error "CanTrcv_43_tja1145a_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h have different vendor IDs"
#endif
/* Check if header file and CanTrcv configuration header file are of the same Autosar version */
#if ((CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_MAJOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_MINOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_AR_RELEASE_REVISION_VERSION_CFG_H))
    #error "AutoSar Version Numbers of CanTrcv_43_tja1145a_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h are different"
#endif
/* Check if header file and CanTrcv configuration header file are of the same software version */
#if ((CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_SW_MAJOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_SW_MINOR_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_SW_MINOR_VERSION_CFG_H) || \
     (CANTRCV_43_TJA1145A_SW_PATCH_VERSION_PBCFG_H != CANTRCV_43_TJA1145A_SW_PATCH_VERSION_CFG_H))
    #error "Software Version Numbers of CanTrcv_43_tja1145a_PBcfg.h and CanTrcv_43_tja1145a_Cfg.h are different"
#endif
[!ENDIF!][!//
[!ENDIF!][!//

/*==================================================================================================
*                                      DEFINES AND MACROS
==================================================================================================*/
/**
*   @brief      Enable/Disable precompile Support
*/
#define CANTRCV_43_TJA1145A_PRECOMPILE_SUPPORT[!WS "22"!][!IF "(IMPLEMENTATION_CONFIG_VARIANT = 'VariantPreCompile' or IMPLEMENTATION_CONFIG_VARIANT='VariantLinkTime') and (variant:size() <= 1)"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!]

/**
*   @brief      The definition represents number of configured ECUC partitions
*/
[!NOCODE!]
    [!VAR "maxCoreDefConfig" = "num:i(1)"!]
    [!IF "CanTrcvGeneral/CanTrcvMulticoreSupport = 'true'"!][!//
        [!IF "node:exists(as:modconf('EcuC')[1]/EcucPartitionCollection/*[1]/EcucPartition)"!][!//
            [!VAR "maxCoreDefConfig" = "num:i(count(as:modconf('EcuC')[1]/EcucPartitionCollection/*[1]/EcucPartition/*))"!]
        [!ENDIF!][!//
    [!ENDIF!][!//
[!ENDNOCODE!]
#define CANTRCV_43_TJA1145A_MAX_PARTITIONS[!WS "26"!]([!"$maxCoreDefConfig"!]U)

/**
*   @brief      Enable/Disable user mode Support
*/
[!NOCODE!]
    [!IF "CanTrcvGeneral/CanTrcvEnableUserModeSupport = 'true'"!][!//
        [!CODE!]#define CANTRCV_43_TJA1145A_ENABLE_USER_MODE_SUPPORT[!WS "16"!](STD_ON)[!CR!][!ENDCODE!]
	[!ELSE!]
		[!CODE!]#define CANTRCV_43_TJA1145A_ENABLE_USER_MODE_SUPPORT[!WS "16"!](STD_OFF)[!CR!][!ENDCODE!]
    [!ENDIF!][!//
[!ENDNOCODE!]

/**
*   @brief      Enable/Disable GetCoreID/Multicore
*/
#define CANTRCV_43_TJA1145A_MULTICORE_ENABLED[!WS "23"!][!IF "num:i(count(CanTrcvGeneral/CanTrcvEcucPartitionRef/*)) > 0"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Wake up support
*/
#define CANTRCV_43_TJA1145A_WAKEUP_SUPPORT[!WS "26"!][!IF "node:value(CanTrcvGeneral/CanTrcvWakeUpSupport) != 'CANTRCV_WAKEUP_NOT_SUPPORTED'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable development error detection and notification
*/
#define CANTRCV_43_TJA1145A_DEV_ERROR_DETECT[!WS "24"!][!IF "node:value(CanTrcvGeneral/CanTrcvDevErrorDetect) = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable diagnostic event manager
*/
#define CANTRCV_43_TJA1145A_DISABLE_DEM_REPORT_ERROR_STATUS[!WS "9"!][!IF "node:value(CanTrcvGeneral/CanTrcvDiagnosticEventManager) = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Enable/Disable support CanTrcv_GetVersionInfo API
*/
#define CANTRCV_43_TJA1145A_VERSION_INFO_API[!WS "24"!][!IF "node:value(CanTrcvGeneral/CanTrcvVersionInfoApi) = 'true'"!](STD_ON)[!ELSE!](STD_OFF)[!ENDIF!][!CR!]

/**
*   @brief      Instance of the CanTrcv Hw unit
*/
#define CANTRCV_43_TJA1145A_INSTANCE[!WS "32"!]((uint8)[!"node:value(CanTrcvGeneral/CanTrcvIndex)"!]U)

/**
*   @brief      Maximum time allowed to the CanTrcv for replying to an SPI command
*/
#define CANTRCV_43_TJA1145A_SPI_COM_TIMEOUT[!WS "25"!]((uint8)[!"node:value(CanTrcvConfigSet/CanTrcvSPICommTimeout)"!]U)

/**
*   @brief      Maximum number of communication retries in case of a failed SPI communication
*/
#define CANTRCV_43_TJA1145A_SPI_COM_RETRIES[!WS "25"!]((uint16)[!"node:value(CanTrcvConfigSet/CanTrcvSPICommRetries)"!]U)

/**
*   @brief      Enable/Disable synchronous SPI communication
*/
#define CANTRCV_43_TJA1145A_SPI_COM_SYNCHRONOUS[!WS "21"!]([!"text:toupper(node:value(CanTrcvConfigSet/CanTrcvSpiAccessSynchronous))"!])

/**
*   @brief      Period of cyclic call to CanTrcv_MainFunction
*/
#define CANTRCV_43_TJA1145A_MAIN_FUNCTION_PERIOD[!WS "20"!](float)[!"node:value(CanTrcvGeneral/CanTrcvMainFunctionPeriod)"!])

/**
*   @brief      Period of cyclic call to CanTrcv_MainFunctionDiagnostics
*/
#define CANTRCV_43_TJA1145A_MAIN_DIAGNOSTIC_FUNCTION_PERIOD[!WS "9"!]((float)[!"node:value(CanTrcvGeneral/CanTrcvMainFunctionDiagnosticsPeriod)"!])

/**
* @brief		SPI level - synchronous transmission
*/
#define CANTRCV_43_TJA1145A_SPI_LEVEL_DELIVERED[!WS "21"!]([!"node:value(CanTrcvConfigSet/CanTrcvSPILevelDelivered)"!]U)

/**
* @brief		Number of connected devices
*/
#define CANTRCV_43_TJA1145A_MAX_DEVICES_NUM[!WS "25"!]((uint32)[!"num:i(count(CanTrcvConfigSet/CanTrcvChannel/*))"!]U)

[!NOCODE!]
[!VAR "cfgCount" = "num:i(count(CanTrcvConfigSet/Configuration/*) - 1)"!]
[!ENDNOCODE!]

[!IF "(IMPLEMENTATION_CONFIG_VARIANT = 'VariantPostBuild' or (variant:size()>1))"!] [!//
/**
*   @brief      CanTrcv external configuration
*/
#define CANTRCV_43_TJA1145A_CONFIG_EXT \
[!IF "var:defined('postBuildVariant')"!][!//
    [!VAR "variantIndex"="0"!]
    [!VAR "variantNumber"="variant:size()"!]
    [!LOOP "variant:all()"!]
        [!VAR "variantIndex"="$variantIndex + 1"!]
        CANTRCV_43_TJA1145A_CONFIG_[!"."!]_PB[!WS!][!IF "$variantIndex < $variantNumber"!]\[!CR!][!ENDIF!]
    [!ENDLOOP!]
[!ELSE!][!//
        CANTRCV_43_TJA1145A_CONFIG_PB
[!ENDIF!][!//
[!ENDIF!][!//


#ifdef __cplusplus
}
#endif

#endif /* _CANTRCV_43_TJA1145A_CFG_H_ */

/** @} */
